// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epaevltzaavepiidrozl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYWV2bHR6YWF2ZXBpaWRyb3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDY3MDgsImV4cCI6MjA2NDg4MjcwOH0.P8PXEMVlm3yXiz0pIvoTXtHTXMvaSP4PlczqfI0TX1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);